model:
  type: PmtC
  options:
    npmts: 4681
    pmt_scale: true
    dropout: 0.02
    nout: 5
    nblocks: 4
    hidden_size: 16
    classifier_size: 128
    factor: 2
    final_hidden_size: 256
    final: tanh01
    offset: [0., 0.]
    scale: [1000., 8.]
    label_offset: [0.0, 0.0, 0.0, 0.0, 0.0]
    label_scale: [1.0, 1.0, 0.1, 0.0005, 0.0005]
    time_mean: False
    update_with_classifer: true

diffusion:
  schedule:
    type: linear  # Options: linear, cosine, quadratic, sigmoid
    beta_start: 0.0001
    beta_end: 0.02
    timesteps: 1000
  objective: "eps"  # Options: eps, x0
  use_cfg: true
  cfg_scale: 2.0
  cfg_dropout: 0.1



training:
  method: wbcosine
  warmup: True
  warmup_proportion: 3.0e-3
  cycle: 2
  nepochs: 20
  bsz: 128
  lr: 0.0003
  loss: l1loss
  early_stopping: 10


data:
  loader: h5
  h5_path: /home/pmj0324/icecube-genesis/0121/GENESIS/GENESIS-data/22644_0921_time_shift.h5
  bsz : 128
  shuffle: true
  num_workers: 3
  angle_conversion: true 
  pin_memory: false



path: ./output/
device: cuda
print_every: 50

